### ISSUE TITLE
Nginx: Permission denied error

### ISSUE THREAD

**Issue by slima** [hardware/rainloop#10]
docker-compose:

```yml
  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    restart: unless-stopped
    volumes:
      - /mnt/docker/rainloop:/rainloop/data
    depends_on:
      - mailserver
      - mariadb
```

docker logs -f rainloop :

```
nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)
2017/08/28 10:40:52 [emerg] 349#349: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)
```

**Comment by hardware** [comment]
Can you try with the last update ? I don't have this error on my end.

https://hub.docker.com/r/hardware/rainloop/builds/

If it does not work, give me the result of `docker info`

**Comment by slima** [comment]
docker info :

```
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 47
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-128-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 993.8MiB
Name: xxx
ID: FJHC:BTBW:Y5YD:V5CE:OLBT:GAJO:GON7:R6BL:L77O:MEY2:A4WA:OXDE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

docker pull hardware/rainloop

```
Using default tag: latest
latest: Pulling from hardware/rainloop
Digest: sha256:bebd0443998f8ce9b0cc110246fb42a86ff54220b842f1ed3bfad63f00a98262
Status: Image is up to date for hardware/rainloop:latest
```

**Comment by hardware** [comment]
Ok nothing wrong in your setup. Can you try this :

```
git clone https://github.com/hardware/rainloop && cd rainloop/
git checkout 33741f7948ed395b7d945c8582b35f839e116fe2
docker build -t hardware/rainloop .
docker-compose up -d
```

And retry.

**Comment by slima** [comment]
Still error.

**Comment by slima** [comment]
What is your host system? and docker version?

**Comment by hardware** [comment]
On my ArchLinux desktop, Kernel 4.12.8-2 with :

- Docker : **17.06.1-ce**
- Storage Driver: **devicemapper**
- Backing Filesystem: **xfs**

On my Debian GNU/Linux 8 (jessie) server, kernel 3.16.0-4-amd64 with :

- Docker : **17.05.0-ce**
- Storage Driver: **aufs**
- Backing Filesystem: **extfs**

Work well for both desktop and server.

**Comment by hardware** [comment]
Someone else has opened a github issue for [hardware/selfoss](https://github.com/hardware/selfoss) with a `Permission denied` error too  and I have no problem : https://github.com/hardware/selfoss/issues/3

This is strange...

@xataz @wonderfall do you have any idea ?

**Comment by Wonderfall** [comment]
This happens with an old aufs driver I'm afraid.
Also this happens sometimes even with other drivers.

That's a part of why my images are now using a self-compiled version of nginx.

**Comment by hardware** [comment]
Ok, that's what I thought, i will try `wonderfall/nginx-php:7.1` to solve this problem.

**Comment by slima** [comment]
Yah, On Ubuntu 16.04 the problem does not occur.

$ docker info
Containers: 7
 Running: 6
 Paused: 0
 Stopped: 1
Images: 7
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 48
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-93-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.3MiB
Name: ...
ID: TKKJ:FVZA:IKNL:NSXX:HIFP:WU22:6R32:WOAL:6BEP:BJYE:LY6R:TRHG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Comment by osiloke** [comment]
Having the same issue, seems like different users. will look into it

**Comment by osiloke** [comment]
changed UID and GID to nginx will work because that user exists, but its not a good solution, i think

**Comment by hardware** [comment]
Oups, Github auto closing this issue with the last commit title.

@osiloke @slima This issue should now be fixed.

**Comment by rellerp** [comment]
I retrieve a "unknown error" on auth...
I'm mounting docker with yours latest image... but not solved
Not auth and no logs... please help me.

**Comment by hardware** [comment]
@rellerp since the last commit ? I haven't any issue. Open a new issue for this problem please and check your mailserver logs.

**Comment by slima** [comment]
I`m informing, issue does not longer occur on Ubuntu 14.04

**Comment by osiloke** [comment]
I'm still getting this error with the latest docker image, but it stops when i add
```
environment:
      - UID=nginx
      - GID=nginx
```
